### ISSUE TITLE
authentication decorator with jwt

### ISSUE THREAD

**Issue by kipierre** [barsifedron/candid-cqrs#21]
hello Mr already a big thank you for the work you have done, but it hurts you Mr, I will use an authentication decorator for my several limited contexts how this decorator is implemented. Arnaud Lemaire talks about this conference ddd-and-cqrs-php-tour-2018.
Thank you for your help I am starting with the cqrs ddd event sourcing on an Insurance project

**Comment by barsifedron** [comment]
Hi

First, I am not myself really familiar with jwt.

But taking this tutorial as an example : https://javatechonline.com/how-to-implement-jwt-authentication-in-spring-boot-project/ (the step 9)


You could do :

1. Add your authentication parameters to your command or to your query.

`UseCaseCommand{

String token;
... your other regular parameters

}`

2. Create a middleware that validates your token like this (pseudo code)

`
public class JwtCommandBusMiddleware implements CommandBusMiddleware {

    private JWTUtil util;
    private UserDetailsService userDetailsService;

    @Inject
    public JwtCommandBusMiddleware(JWTUtil util, UserDetailsService userDetailsService) {
        this.util = util;
        this.userDetailsService = userDetailsService;
    }

    @Override
    public <T> CommandResponse<T> dispatch(Command<T> command, CommandBus next) {

        // Reading Token from Authorization Header
        String token = command.token;
        if (token == null) {

            // throw an error

        }

        String username = util.getSubject(token);

        if (username == null) {

            // throw an error

        }

        //if username is not null & Context Authentication must be null
        UserDetails user = userDetailsService.loadUserByUsername(username);
        boolean tokenIsValid = util.isValidToken(token, user.getUsername());
        if (!tokenIsValid) {

            // throw an error
        }

        // if you are here, then your token is valid.
        // just dispatch to the next middleware in line
        return next.dispatch(command);
    }
}`

you would need one for your commands and one for your queries.


3. Change your [CommandBusFactory](https://github.com/barsifedron/candid-cqrs/blob/master/happy-neighbourhood-spring-shell/src/main/java/com/barsifedron/candid/cqrs/happy/shell/utils/cqrs/command/CommandBusFactory.java)  and/or [QueryBusFactory](https://github.com/barsifedron/candid-cqrs/blob/master/happy-neighbourhood-spring-shell/src/main/java/com/barsifedron/candid/cqrs/happy/shell/utils/cqrs/query/QueryBusFactory.java) to add this middleware in the chain

`
        return CommandBusMiddleware
                .compositeOf(
                        ...
                        jwtCommandBusMiddleware, // !!!!
                        transactionalMiddleware,
                        new DomainEventsDispatcher(domainEventBus))
                .decorate(new MapCommandBus(commandHandlersRegistry.handlers()));
`

**Comment by barsifedron** [comment]
Secondly, regarding event sourcing, while I believe this bus can be used for it, I personnaly did not do it and deliberately chose not to support this in this project exemples.

I would be happy to get feedback, if you ever chose to.

**Comment by kipierre** [comment]
thank you very much Mrs Jean Michel for the this answer she is exactly what i wanted

**Comment by kipierre** [comment]
and yes we will do event sourcing and I will get back to you soon

**Comment by barsifedron** [comment]
Another alternative, In the case where you want authentication only some of the time, you could also use a marker interface

```java
public interface CommandToAuthenticate {
    String getToken();
}
```

```java
public class UseCaseCommand implements Command<NoResult>, CommandToAuthenticate {

    private String token;

    // .. your other params

    @Override
    public String getToken() {
        return token;
    }
}
```

```java
public class JwtCommandBusMiddleware implements CommandBusMiddleware {

    private JWTUtil util;
    private UserDetailsService userDetailsService;

    @Inject
    public JwtCommandBusMiddleware(JWTUtil util, UserDetailsService userDetailsService) {
        this.util = util;
        this.userDetailsService = userDetailsService;
    }

    @Override
    public <T> CommandResponse<T> dispatch(Command<T> command, CommandBus next) {

        if (!CommandToAuthenticate.class.isAssignableFrom(command.getClass())) {
            // no need to authenticate the command.
            // pass to the next middleware in line
            return next.dispatch(command);
        }

        // if here, your command requires authentication
        // ... proceed as decribed above
    }
```

This is obviously more complex but, in exchange, it gives you the flexibility to decide if a command should or not be authenticated.

**Comment by kipierre** [comment]
this is correct and thank you again for anticipating this problem for us

    Le jeudi 11 février 2021 à 09:01:28 UTC+1, Jean-Michel Tonneau <notifications@github.com> a écrit :  
 
 


Another alternative, In the case where you want authentication only some of the time, you could also use a marker interface
public interface CommandToAuthenticate {
    String getToken();
}public class UseCaseCommand implements Command<NoResult>, CommandToAuthenticate {

    private String token;

    // .. your other params

    @Override
    public String getToken() {
        return token;
    }
}public class JwtCommandBusMiddleware implements CommandBusMiddleware {

    private JWTUtil util;
    private UserDetailsService userDetailsService;

    @Inject
    public JwtCommandBusMiddleware(JWTUtil util, UserDetailsService userDetailsService) {
        this.util = util;
        this.userDetailsService = userDetailsService;
    }

    @Override
    public <T> CommandResponse<T> dispatch(Command<T> command, CommandBus next) {

        if (!CommandToAuthenticate.class.isAssignableFrom(command.getClass())) {
            // no need to authenticate the command.
            // pass to the next middleware in line
            return next.dispatch(command);
        }

        // if here, your command requires authentication
        // ... proceed as decribed above
    }
This is obviously more complex but, in exchange, it gives you the flexibility to decide if a command should or not be authenticated.
