### ISSUE TITLE
Domain and  ManyToMany relationships

### ISSUE THREAD

**Issue by tebuco** [barsifedron/candid-cqrs#26]
another question please how to implement a many to many relation without polluting the domain with the hibernate annotation
for OneToMany relationships you make lists
but what about ManyToMany relationships

**Comment by barsifedron** [comment]
This question is not really related to this project.
What I mean is that the use of a command bus / CQRS should not really change how you model your entities.
If you don't like hibernate annotations, you can always use the xml configuration.
I personaly do not bother with this and choose to accept the annotations as a minimum invasion of the domain.

What matters more I think is the modelling of @ManyToMany as this could be a bad idea depending on your use cases.

Here are some links I encountered in the past about this:

https://udidahan.com/2009/01/24/ddd-many-to-many-object-relational-mapping/

https://www.dddcommunity.org/library/vernon_2011/

https://vladmihalcea.com/the-best-way-to-map-a-many-to-many-association-with-extra-columns-when-using-jpa-and-hibernate/

**Comment by barsifedron** [comment]
Question is orthogonal to command bus/ cqrs concepts
